### PR TITLE
Add code necessary to work with Unicode

### PR DESCRIPTION
**Pull request by mehdisadeghi**
This PR contains Public Domain code from Jeff Bezanson to work with utf8 and LGPL code from GLib Project (from GNOME) to work with Unicode strings. I have removed unused code from both.

### CODE REVIEW

**Comment by gl00my** [comment]
I am not sure, can we include lgpl code in mit code?
I found this somewhere on stackoverflow:

LGPL — stands for Lesser GPL (used to mean Library GPL). The significant difference with GPL is, that it doesn't impose the license on software using the library. Only if you'd modify the library or directly include parts of the code in your software, then your code would have to be LGPL. 

So, we include part of it into code, can you explain this situation?

**Comment by gl00my** [comment]
I have readed some papers and it is still unclear for me. Its like that we should change to dual license: mit/lgpl? Can be this code rewriten or derived from project with compatible license?
I have already rewrote part of code to free my project and currently i am trying to include only mit/bsd code to avoid license problems.

**Comment by gl00my** [comment]
https://www.gnu.org/licenses/gpl-faq.html

For example, here you can read that you should give way to link you application even statically. So, someone will not able just close sources. Someone should give object files...  This totally brake mit license. So, we should find another realisation or write own.

**Comment by gl00my** [comment]
Hmm... Sdl_anigif.c is lgl too... I should think about all this.

**Comment by mehdisadeghi** [comment]
I also read a lot before posting. There is already some LGPL code inside the repository, so I thought it is okay.

I don't think that we can rewrite this. Multilingual Unicode is hard.

**Comment by mehdisadeghi** [comment]
> LGPL — stands for Lesser GPL (used to mean Library GPL). The significant difference with GPL is, that it doesn't impose the license on software using the library. Only if you'd modify the library or directly include parts of the code in your software, then your code would have to be LGPL.

I read a lot, most people talk about libraries, but your project is a binary. Perhaps it is possible to put the RTL code under LGPL? Linking to GLib does not work becaues it has so many unnecessary dependencies. It will not work on Android for example. I will think more about this too.

**Comment by mehdisadeghi** [comment]
I am reading [LGPL 2.1](https://opensource.org/licenses/LGPL-2.1) text. It is easy to understand.

> If identifiable sections of that work are not derived from the Library, and can be reasonably considered independent and separate works in themselves, then this License, and its terms, do not apply to those sections when you distribute them as separate works.

Instead is not "derived" from this library. It does not even depend on it, unless the compile flag is set. The codes are in different files with copyright header (I have to add change dates though).

> However, linking a "work that uses the Library" with the Library creates an executable that is a derivative of the Library (because it contains portions of the Library), rather than a "work that uses the library". The executable is therefore covered by this License. 

So if Instead is compiled with portions of GLib, "the executable" must be under LGPL. I think this is good. It means that if the compile flag is not set (the default), the executable will be free of any LGPL code, and therfore can be under MIT.

This section is interesting too:

> 6. As an exception to the Sections above, you may also combine or link a "work that uses the Library" with the Library to produce a work containing portions of the Library, and distribute that work under terms of your choice, provided that the terms permit modification of the work for the customer's own use and reverse engineering for debugging such modifications.

> You must give prominent notice with each copy of the work that the Library is used in it and that the Library and its use are covered by this License. You must supply a copy of this License. If the work during execution displays copyright notices, you must include the copyright notice for the Library among them, as well as a reference directing the user to the copy of this License.

**Comment by mehdisadeghi** [comment]
Here is an unofficial LGPL 3 translation http://antirao.ru/gpltrans/lgplru.pdf

**Comment by gl00my** [comment]
Is this code needed to future PRs? For isalpha or like so?

**Comment by mehdisadeghi** [comment]
> Is this code needed to future PRs? For isalpha or like so?

Yes. I have used it to recognize the script of each unicode character in words and whether it is a digit or an alphabet. Based on this information, then I call TTF_SetDirection and TTF_SetScript for each word.

btw, two of the files in these PR are generated files, `gunichartables.h` and `gscripttable.h`. only `gunicode.h` and `guniprops.c` contain code.

**Comment by gl00my** [comment]
Ok, just let's move at this stage. :)

**Pull request merged**
