### PR TITLE
Add language specific fonts

### PR DESCRIPTION
**Pull request by mehdisadeghi**
This PR is the first in a small series of PRs to add basic support for RTL languages (Persian) to INSTEAD. Part of #76.

Since the current default theme and all other themes which depend on it use the LiberationSans font, it is impossible to render Arabic text with INSTEAD. This PR makes it possible to add one font per language to each theme. For example if there is `-lang fa` option and there is a file `fa-sans.ttf` in the theme folder, it will be used to render game text.

The benefit of this simple approach is that everything else works and we don't need to change themes and they will just work.

This PR also adds NotoSansArabicUI-Light.ttf, NotoSansArabicUI-Black.ttf, NotoSansArabicUI-Bold.ttf and NotoSansArabicUI-Regular.ttf as fa-sans-i.ttf, fa-sans-bi.ttf, fa-sans-b.ttf and fa-sans.ttf respectively.

### CODE REVIEW

**Comment by gl00my** [comment]
1. The idea of themes is that theme completly defines the look of the game. Any game can include own theme (subdirectory theme/ or theme.ini) So, it is not a good idea to force using lang-specific fonts, while game contains own theme... 

2. Language of the INSTEAD interface is not the same as the language of the game...

So, it is supposed, that if you are writing game. For example, you are translating Return Of The Quantum Cat to Arabic, you just make own theme for this game, that includes font with Arabic glyphs and thats all... You put this theme inside the game and all works fine. Theme can includes own fonts.

Currently i have made branch right-to-left and i will merge you pr's here. Then i will check again for cherry-pick.

If you want, i can merge this pr too, but what do you think about  my arguments?

**Comment by gl00my** [comment]
For example, there is the jp version of return of the quantum cat. Font is included in game own theme: https://sourceforge.net/projects/instead-games/files/instead-cat_jp-1.1.zip/download

**Comment by gl00my** [comment]
Ok, i found that this PR can in theory solve the interface language problem. 
What will happen in such situation?

1) instead interface setting is Arabic
2) game included theme contain english-only fonts for menu and game itself;
3) what font will be used? I think, the english-only from game?

**Comment by gl00my** [comment]
Ok, i got it. Merget into right-to-left branch

**Comment by mehdisadeghi** [comment]
@gl00my oh thanks for the quick reply, I was just going to reply slowly... 

> The idea of themes is that theme completly defines the look of the game. Any game can include own theme (subdirectory theme/ or theme.ini) So, it is not a good idea to force using lang-specific fonts, while game contains own theme...

Good to know that games can define their own theme and font. I didn't know this! I didn't create a new theme because I realized if I make a new theme the already existing themes will not work for Arabic script (Persian uses Arabic text, the same way many languages use Latin script...), so I though maybe adding this option is useful to take advantage of already existing themes.

> Language of the INSTEAD interface is not the same as the language of the game...

Yes, I noticed that. In fact I have already translated the menus. I understand how INSTEAD renders a script such as Arabic is independent from the user interface language. Ideally, INSTEAD should render any text correctly, independent from the user interface language. But I did not find a simple way to do this, therefore I used the already existing `-lang` as a "hack". Other programs such as Firefox get fonts information from the operating system. But it is complicated and INSTEAD is already working just fine...

> So, it is supposed, that if you are writing game. For example, you are translating Return Of The Quantum Cat to Arabic, you just make own theme for this game, that includes font with Arabic glyphs and thats all... You put this theme inside the game and all works fine. Theme can includes own fonts.

This is very good. However, it is good to be able to use already existing themes for Arabic and Persian too. With language-specific fonts it possible... 

> Currently i have made branch right-to-left and i will merge you pr's here. Then i will check again for cherry-pick.

Great!

> If you want, i can merge this pr too, but what do you think about my arguments?

Thanks for already merging! I agree with you. My intention is to add rtl support to INSTEAD with minimum amount of change and not breaking anything that already works.

> For example, there is the jp version of return of the quantum cat. Font is included in game own theme: https://sourceforge.net/projects/instead-games/files/instead-cat_jp-1.1.zip/download

Thanks! I'll check it out.

> Ok, i found that this PR can in theory solve the interface language problem.
What will happen in such situation?

    instead interface setting is Arabic
    game included theme contain english-only fonts for menu and game itself;
    what font will be used? I think, the english-only from game? Or it's like it will take font from base theme?

The way I implemented this, if the `-lang` option is set to a language such as `fa` and there is a font prefixed with `fa` in the theme directory, it will "overrite" whatever default theme was going to be used.

**Comment by mehdisadeghi** [comment]
One problem I forgot to mention is the mixture of different languages. If a game contains English and Japanese or Russian and Persian, complexities of rendering aside, choosing the right font will be a problem. For example the LiberationSans does not contain any glyphs for Arabic and NotoSansArabic font does contain any glyphs for Latin...

**Comment by gl00my** [comment]
> One problem I forgot to mention is the mixture of different languages. 
Yes, but we can't do anything with it.
BTW there is a module 'fonts' for INSTEAD, that can be used to mix different fonts in scene, it uses sprites to render text. So, in theory, it can be solution for the specific game...

**Comment by mehdisadeghi** [comment]
> BTW there is a module 'fonts' for INSTEAD, that can be used to mix different fonts in scene, it uses sprites to render text. So, in theory, it can be solution for the specific game...

Interesting. I saw sprite in the code but I didn't understand why it is there. Meanwhile, I found a simple solution for the problem. I will upload another font that covers Latin and Arabic. So one font will show most games correctly.

**Comment by gl00my** [comment]
In fact, i am not sure it is a good idea.
There are a lot of languages in unicode. We can not add them all. So, you will add Arabic, then we will add Japaneese and so on... INSTEAD still works even on S60 so it is not right way, imo.

I thinking, that i will merge you LRO logic to engine, but i am not sure about the interface. May be the good idea is to make expansion pack (zip file) with fonts and language ini files. So, you will able to create language specific distributions.

Anyway, specific game can still include own theme.

**Comment by mehdisadeghi** [comment]
Thanks for the explanation. I have nothing against it! Just trying to figure out the simplest way to support Arabic text along other texsts. I'll try to add the fonts to the persian translation of the quantum cat. See the pictures below.

> src/sdl-instead ../../instead-cat-1.6.1 -lang fa
image

> src/sdl-instead ../../instead-cat-1.6.1
image

**Comment by mehdisadeghi** [comment]
> I think, that i will merge you RTL logic to engine, but i am not sure about the interface.

There is one problem that I haven't found a good solution for it yet. The language of the interface should be independent of the game. But how should we figure out the language of a game? So far I tried using `-lang` option. However, as you already mentioned, it is not suitable for the games because it is only about the interface and menus.

Is is possible to add the language and direction to the game as metadata? I see games have already some metadata such as `game.codepage="UTF-8";`. Is it possible to add something like `game.codepage="fa_IR.UTF-8"` or `game.lang="fa";`?

In order to correctly render a piece of text with HarfBuzz one need at least two things:

 1. language of the text
 2. direction of the text

There are projects such as [fribidi](https://github.com/fribidi/fribidi) which do this. They figure out the right direction and language of a piece of text which we can use to render it correctly. So far I did not use fribidi, since it is currently enough for me just to know the direction and language of the text.

What do you think @gl00my ? Is there a simple way to know the language of a game without using `-lang` parameter (and keep -lang only for the interface)?

**Comment by gl00my** [comment]
I see. There are info  tags in main3.lua (or main.lua for legacy api)
It has --$TAGNAME: value syntax.
Lilke: --$Name: This is my game!$
Or --$Author: Anonymous

Look game_tag() in src for example. There are also lang specific tags:

--$Name: Game$
--$Name[ru]: Игра$

I think it is not bad place to add language specific info.

game.codepage or like can be used too, but i think it is better to not break compatibility. So, UTF-8 and fa_IR.UTF-8 should work.

I am not sure if it the best solution. but now i think the better choice is:

--$Language: fa
--$Lang-dir: rtl 

Or like so.... Because we can get this info before running game.

What do you think?

**Comment by gl00my** [comment]
But can there be a fallback mode for legacy games? Defaults to LTR and no language info?

**Comment by mehdisadeghi** [comment]
> --$Language: fa
I think having a `language` tag is enough four our basic use case. So far I only know three right to left languages in the world: Arabic, Farsi (Persian) and Hebrew. So, knowing the language is enough to know the basic direction of the text. (however, this will not solve the problem of mixing different languages and math which we can fix later if necessary).

> But can there be a fallback mode for legacy games? Defaults to LTR and no language info?
Definitely! I see what I can do :)

**Comment by gl00my** [comment]
btw, here is the module i talked about: https://github.com/instead-hub/stead3-modules/tree/master/fonts

About mixing the languages on scene, i suppose, the font subsystem must be rewritten. So, may be it is good idea just to add rtl first. :)

**Comment by mehdisadeghi** [comment]
I think the quantum cat is using STEAD2? Because when I renamed `main.lua` to `main3.lua` it produced an error. So where should I add the new tag? STEAD2 or STEAD3...

**Comment by gl00my** [comment]
I think tags logic is universal for stead2 and stead3 api. 
Check game_tag() function - it works for both main and main3 files
Just use this function.

**Comment by mehdisadeghi** [comment]
I added the tag in #78

**Pull request merged**
