### PR TITLE
Add Farsi Menus

### PR DESCRIPTION
**Pull request by mehdisadeghi**
I have the following changes in this PR:

- Adding Farsi lang menu
- Increasing the inventory size (see pictures.)
- Replacing the font with dejavusans. The other font does not have the symbols and renders boxes instead. (I did not any other font with enough glyphs to correctly display game menus and text).

Feel free to pick what makes sense. I tried different themes and slightly increased the inventory width to decrease the margin on the right hand.

You can try my Farsi translation here: https://github.com/mehdisadeghi/returning-the-quantum-cat/ (work in progress). However, you have to compile SDL_ttf with a flag (change [this line](https://hg.libsdl.org/SDL_ttf/file/72b8861dbc01/SDL_ttf.c#l40) to 1).

Normal inventory
Screenshot-20200901210535-802x639

Wide inventory
Screenshot-20200901210420-802x639

Menus
Screenshot-20200903232521-802x639

Without dejavusans
Screenshot-20200903233310-802x639

#76

### CODE REVIEW

**Comment by gl00my** [comment]
Sorry, we can not change standard themes. There are a lot of games that inherits them (changing something) and new geometry can broke them (for example, background picture is adjusted to geometry).

So, i suppose, the game itself should include own theme (and font), as we talked early.

What about language file (fa.ini)? I think, we should make language pack and ship it separated. Or, may be, make language files to be part of the theme. (Currently, they can not be part of theme, but in theory we could write it)

**Comment by mehdisadeghi** [comment]
@gl00my That's fine, I just wanted to publish what I had change so you can try it. For the fonts though, I think INSTEAD should be able to load multiple fonts to support a wider range of scripts, currently a game can not have different symbols or scrypts.


Now I have no more changes. Maybe one more to update copyright notices. 

So what do you think? Where you able to try this branch? Is there anything else necessary from my side?

**Comment by gl00my** [comment]
Ok, should i try it with SDL_ttf from hg? i will test it and try to cleanup
some staff. Then will write you. Thanks!

пт, 4 сент. 2020 г., 13:51 Mehdi Sadeghi <notifications@github.com>:

**Comment by mehdisadeghi** [comment]
> should i try it with SDL_ttf from hg?

Yes, that version supports HarfBuzz.

>  i will test it and try to cleanup
some staff

Nice! I'm looking forward to hearing your feedback.

**Comment by gl00my** [comment]
Sorry for long delay. I am just today compiled rtl branchm run cat and start looking in code... I am not sure how long time it will take, but i will review code anyway.

**Comment by gl00my** [comment]
Ok, i began to cleanup code, please, check if it slitll works as it should work.

And i see that Arabic script is hardcoded. in ->script = HB_SCRIPT_ARABIC; Is it ok? Or we can detect script from words?

**Comment by gl00my** [comment]
I have decided to link with system glib and commited it. Can you update cmake rules to link with glib if HarfBuzz is enabled?

**Comment by gl00my** [comment]
in ->script = HB_SCRIPT_ARABIC; 
May be we can take this from language of game? Or maybe glib can detect script? So, there are 2 problems and i need help:

1) ->script Arabic hardcoded 
2) cmake glib depenence while HarfBuzz enabled

**Comment by gl00my** [comment]
Oh, about 1 case i did not see: case G_UNICODE_SCRIPT_ARABIC
So, we can just add all rtl languages  here?

**Comment by gl00my** [comment]
Ok. What i did:
1) CMAKE find glib
2) removed lang-font code. Sorry it is not for stable versiob
3) removed game lang code,
4) refactoring
5) fix keyboard navigation

**Comment by mehdisadeghi** [comment]
> Sorry for long delay. I today compiled rtl branchm

sorry for my long delay too! I was away from computers for a while!

> Arabic script is hardcoded. in ->script = HB_SCRIPT_ARABIC; Is it ok? Or we can detect script from words?

That is what we do. If the script is Arabic we set w->script to Arabic for later user (in order not to run all the checks everytime).

> I have decided to link with system glib and commited it. 

That is definitely better than copy/pasting glib code. Will this solution work on Android?

> Can you update cmake rules to link with glib if HarfBuzz is enabled?

I get a coredump:

```
Opening game: ../../instead-cat-1.6.1
Video mode: 800x600@32bpp (opengl)
sdl-instead: ../harfbuzz/src/hb-shape-plan.cc:208: hb_shape_plan_t* hb_shape_plan_create2(hb_face_t*, const hb_segment_properties_t*, const hb_feature_t*, unsigned int, const int*, unsigned int, const char* const*): Assertion `props->direction != HB_DIRECTION_INVALID' failed.
[1]    728220 abort (core dumped)  src/sdl-instead ../../instead-cat-1.6.1 -lang fa
```

> n ->script = HB_SCRIPT_ARABIC; May be we can take this from language of game?

No, it will not work. A text may contain words and numbers in different languages, so this should be considered word-by-word.

>  ->script Arabic hardcoded

As I mentioned earlier, it is just stored inside word for further use. Otherwise everytime we have to run the same checks. It is also inside a switch case, because I know two scripts (three languages) which are right-to-left. Arabic (Arabic and Persian), Hebrew. In this PR I added support for Arabic and Persian.

>   cmake glib depenence while HarfBuzz enabled

I will look into this, however I don't know whether it works on Android or not.

> Oh, about 1 case i did not see: case G_UNICODE_SCRIPT_ARABIC
> So, we can just add all rtl languages here?

There is also G_UNICODE_SCRIPT_HEBREW which is an rtl language. It is possible to add another case for it. But I don't read and understand it so I can not help with that.

> removed lang-font code. Sorry it is not for stable versiob

No problem. Menus still would need a solution.

> fix keyboard navigation

Would you mind explaining the problem?

Thanks.

**Comment by gl00my** [comment]
> That is definitely better than copy/pasting glib code. Will this solution work on Android?
I do not know, but i think it is question to android port. I think that we will be able link with .a anyway,

> I get a coredump:
> 
> ```
> Opening game: ../../instead-cat-1.6.1
> Video mode: 800x600@32bpp (opengl)
> sdl-instead: ../harfbuzz/src/hb-shape-plan.cc:208: hb_shape_plan_t* hb_shape_plan_create2(hb_face_t*, const hb_segment_properties_t*, const hb_feature_t*, unsigned int, const int*, unsigned int, const char* const*): Assertion `props->direction != HB_DIRECTION_INVALID' failed.

Can you debug it? I can not reproduce.  :( I run your version of cat w/o valgrind warnings. That bad... :(

> > cmake glib depenence while HarfBuzz enabled
> 
> I will look into this, however I don't know whether it works on Android or not.
I am not sure. I am not author of android port.

> > fix keyboard navigation
> 
> Would you mind explaining the problem?

Games can be played from keyboard. Pressing arrow keys, tab, shift+tab and enter. Without mouse.

**Comment by gl00my** [comment]
I hope i fixed this, try pull.

**Comment by mehdisadeghi** [comment]
@gl00my thanks for the quick update. I will check this as soon as possible. I was thinking whether it is possible to automatically link against glib and HarfBuzz if they are available on the system. That way, at least on desktops, this feature will be enabled and rtl games will work without extra configurations. What do you think?

**Comment by gl00my** [comment]
> @gl00my thanks for the quick update. I will check this as soon as possible. I was thinking whether it is possible to automatically link against glib and HarfBuzz if they are available on the system. 

But is there a solution to check if SDL_ttf is compiled with HarfBuzz?

**Comment by mehdisadeghi** [comment]
When I run `cmake -DCMAKE_INSTALL_PREFIX=~/.local/ -DWITH_HARFBUZZ=1 -DWITH_GTK3=0 ..` and then make I get `hb.h` not found error. I will check again though.

> But is there a solution to check if SDL_ttf is compiled with HarfBuzz?

Oh, you're right. That's a problem. I have to see, or ask the author.

**Comment by mehdisadeghi** [comment]
@gl00my if SDL_ttf is not compiled with HarfBuzz it will always return -1 when setting script and direction. This is from SDL_ttf code:

```
/* Harfbuzz */
int TTF_SetDirection(int direction) /* hb_direction_t */
{
#if TTF_USE_HARFBUZZ
    g_hb_direction = direction;
    return 0;
#else
    (void) direction;
    return -1;
#endif
}

int TTF_SetScript(int script) /* hb_script_t */
{
#if TTF_USE_HARFBUZZ
    g_hb_script = script;
    return 0;
#else
    (void) script;
    return -1;
#endif
}
```

**Comment by gl00my** [comment]
But to detect that it is neccessary to build test application while configure (or cmake phase). I am not sure if it is clean solution. I think, dependency and configure staff is up to mantainers. Untill new SDL_ttf will out and we will able to detect rtl in runtime.

**Comment by mehdisadeghi** [comment]
> I think, dependency and configure staff is up to mantainers. Untill new SDL_ttf will out and we will able to detect rtl in runtime.

I get your point. That's the right think to do.

**Comment by mehdisadeghi** [comment]
@gl00my did you succeed in trying the translated game?

I found no easy way to check whether SDL_ttf is compiled with HarfBuzz. I will ask on Arch Linux forum to see we can change the default at least on Arch Linux (if possible). So far in order to compile SDL_ttf with HarfBuzz enabled I do:

    $ ./configure CPPFLAGS=-DTTF_USE_HARFBUZZ=1

I also added a font to the game (owntheme) so you should be able to see it correctly.

Please let me know if I can help with anything.

**Comment by gl00my** [comment]
> Please let me know if I can help with anything.
Yes, i successfully run your translation (i have added fonts in theme). Can you confirm, that currently state of branch is good for you?

**Comment by mehdisadeghi** [comment]
@gl00my I'm playing the game currently (as I'm translating the last chapter) with your branch. So far it looks good. I will comment if I face any major issue. Thanks.

**Comment by btimofeev** [comment]
> I have decided to link with system glib and commited it.
>That is definitely better than copy/pasting glib code. Will this solution work on Android?

Glib is not included in Android. Most likely there will be some problems with the build for Android. I tried to compile version 2.24.1 yesterday (not entirely, but only gmodule.so and glib.so). The code is compiled and works in a 32-bit library, but immediately crashes in a 64-bit one. I don’t know yet the problem is this glib itself or the code that uses it (I was compiling the XDelta1 application in this case).

**Comment by mehdisadeghi** [comment]
Hi @btimofeev, thanks for the info. Do you think it is possible to cross compile glib and add it to the Android source? I am going to anyway try the Android build with my changes and HarfBuzz. SDL_ttf already comes with a copy of HarfBuzz in its repo for Android I gueas. If glib does not compile I'll pehaps simply add the necessary glib portions enough to compile.

**Comment by btimofeev** [comment]
@mehdisadeghi I'll clarify: everything that I wrote above refers to the compiled Glib specifically for android. What parts of the glib do you need?

**Comment by mehdisadeghi** [comment]
@btimofeev 

> What parts of the glib do you need?

Infact I don't need most of GLib, only enough to make the function call work:

- Auto generated file: [gscripttable.h](https://github.com/mehdisadeghi/instead/blob/master/src/gscripttable.h)
- Auto generated file: [gunichartables.h](https://raw.githubusercontent.com/mehdisadeghi/instead/master/src/gunichartables.h)
- Definitions: [gunicode.h](https://github.com/mehdisadeghi/instead/blob/master/src/gunicode.h)
- Functions: [guniprops.c](https://github.com/mehdisadeghi/instead/blob/master/src/guniprops.c)

These files have no other dependency.

**Comment by btimofeev** [comment]
If there are no dependencies, then it will be easier to copy these files to the Instead launcher sources.

**Comment by gl00my** [comment]
Ok, i have added Direction tag. Now you can write --$Direction: rtl or --$Direction: auto in theme.ini and it will render in rtl mode or in auto mode (your patch logic).
I am ready to merge it if all seems ok.

**Comment by mehdisadeghi** [comment]
That sounds a good move forward @gl00my! However, I get an error with any command now:

    No languages found in: lang/.

Do you have any idea why?

**Comment by gl00my** [comment]
> No languages found in: lang/.
> ```
> 
> Do you have any idea why?

Just strace it with -e file. It's like that instead can't find lang/ directory.

**Comment by mehdisadeghi** [comment]
Sorry, my bad. I deleted the build directory and reconfigured and it worked. However, now I have another problem. 

What are the right cmake configurations to compile with GLIB and HarfBuzz? I tried the following and it compiles but does not work correctly (no RTL):

### This one compiles but no RTL
    cmake -DCMAKE_INSTALL_PREFIX=~/.local/ -DWITH_HARFBUZZ=1 .. && make

#### Logs:

```
~/Projects/instead_fun/instead/build(right-to-left ✗) cmake -DCMAKE_INSTALL_PREFIX=~/.local/ -DWITH_HARFBUZZ=1 .. && make
...
-- Found Lua51: /usr/lib/liblua.so;/usr/lib/libm.so (found version "") 
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11") 
-- Found SDL2: -I/usr/include/SDL2, /usr/lib/libSDL2.so
-- Found SDL2_mixer: -I/usr/include/SDL2, /usr/lib/libSDL2_mixer.so
-- Found SDL2_image: -I/usr/include/SDL2, /usr/lib/libSDL2_image.so
-- Found SDL2_ttf: -I/usr/local/include/SDL2, /usr/local/lib/libSDL2_ttf.so
-- Found Iconv: -I/usr/include, library not needed
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.7.3") 
-- Checking for module 'gtk+-3.0'
--   Found gtk+-3.0, version 3.24.23
-- Found GTK3: ...
-- Found HarfBuzz: -I/usr/include/harfbuzz, /usr/lib/libharfbuzz.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mx/Projects/instead_fun/instead/build
Scanning dependencies of target sdl-instead
[  3%] Building C object src/CMakeFiles/sdl-instead.dir/SDL_anigif.c.o
...
/home/mx/Projects/instead_fun/instead/src/graphics.c: In function ‘word_detect_rtl’:
/home/mx/Projects/instead_fun/instead/src/graphics.c:3030:14: warning: this statement may fall through [-Wimplicit-fallthrough=]
 3030 |    w->script = HB_SCRIPT_HEBREW;
      |    ~~~~~~~~~~^~~~~~~~~~~~~~~~~~
/home/mx/Projects/instead_fun/instead/src/graphics.c:3031:3: note: here
 3031 |   case G_UNICODE_SCRIPT_ARABIC:
      |   ^~~~
...
[100%] Built target sdl-instead
```

### Does not compile (can not fild hb.h)
    cmake -DCMAKE_INSTALL_PREFIX=~/.local/ -DWITH_HARFBUZZ=1 -DWITH_GTK3=0 .. && make

#### Logs
```
~/Projects/instead_fun/instead/build(right-to-left ✗) cmake -DCMAKE_INSTALL_PREFIX=~/.local/ -DWITH_HARFBUZZ=1 -DWITH_GTK3=0 .. && make
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at doc/CMakeLists.txt:21 (MESSAGE):
  This distribution lacks some documentation files:
  stead3-ru.pdf;modules3-ru.pdf;stead3-en.pdf;instead.txt.  These may be
  generated (network access and additional tools required, see doc/makepdfs),
  or you may use instead source tarball from sourceforge which has these
  files included


-- Performing Test WEXTRA_FLAG_SUPPORTED
-- Performing Test WEXTRA_FLAG_SUPPORTED - Success
-- Performing Test WNO_UNUSED_PARAMETER_FLAG_SUPPORTED
-- Performing Test WNO_UNUSED_PARAMETER_FLAG_SUPPORTED - Success
-- Found Lua51: /usr/lib/liblua.so;/usr/lib/libm.so (found version "") 
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11") 
-- Found SDL2: -I/usr/include/SDL2, /usr/lib/libSDL2.so
-- Found SDL2_mixer: -I/usr/include/SDL2, /usr/lib/libSDL2_mixer.so
-- Found SDL2_image: -I/usr/include/SDL2, /usr/lib/libSDL2_image.so
-- Found SDL2_ttf: -I/usr/local/include/SDL2, /usr/local/lib/libSDL2_ttf.so
-- Found Iconv: -I/usr/include, library not needed
-- Found HarfBuzz: -I/usr/include/harfbuzz, /usr/lib/libharfbuzz.so
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.7.3") 
-- Checking for module 'glib-2.0'
--   Found glib-2.0, version 2.66.2
-- Found GLIB: -I/usr/include/glib-2.0;/usr/lib/glib-2.0/include, /usr/lib/libglib-2.0.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mx/Projects/instead_fun/instead/build
Scanning dependencies of target sdl-instead
[  3%] Building C object src/CMakeFiles/sdl-instead.dir/SDL_anigif.c.o
[  6%] Building C object src/CMakeFiles/sdl-instead.dir/SDL_gfxBlitFunc.c.o
[ 10%] Building C object src/CMakeFiles/sdl-instead.dir/SDL_rotozoom.c.o
[ 13%] Building C object src/CMakeFiles/sdl-instead.dir/config.c.o
[ 16%] Building C object src/CMakeFiles/sdl-instead.dir/game.c.o
[ 20%] Building C object src/CMakeFiles/sdl-instead.dir/graphics.c.o
/home/mx/Projects/instead_fun/instead/src/graphics.c:33:10: fatal error: hb.h: No such file or directory
   33 | #include <hb.h>
      |          ^~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/sdl-instead.dir/build.make:147: src/CMakeFiles/sdl-instead.dir/graphics.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:299: src/CMakeFiles/sdl-instead.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

```

Am I missing something?

**Comment by gl00my** [comment]
Ah, thanks. cmake is too difficult for me, so i used makefiles to test. :) 
I fixed this problem, please pull and retry.

After successful compiling, add --$Direction: auto instead $Language tag and it should work.
Another option: --$Direction: rtl -- force rtl.

**Comment by mehdisadeghi** [comment]
> Ah, thanks. cmake is too difficult for me, so i used makefiles to test. :)

Yeah, I have been also pulling out my hair trying to figure out how to use it :) [This](https://llvm.org/docs/CMakePrimer.html) short intro was surprisingly helpful.

I tried your latest changes and when I set `-- $Direction: auto` in `main.lua` it renders correctly. It looks good to me! :+1:

**Comment by gl00my** [comment]
Merged.

**Comment by mehdisadeghi** [comment]
@gl00my Thanks!

**Pull request closed without merging**
